services:
  captcha_backend:
    build:
      context: ../server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  
    image: captcha_backend:latest
    restart: always
    develop:
      watch:
        - action: rebuild
          path: ../server