services:
  captcha_backend:
    build:
      context: ../server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  
    image: captcha_backend:latest
    restart: always
    develop:
      watch:
        - action: rebuild
          path: ../server
    networks:
      - captcha

  frontend-react:
    build:
      context: ../frontend
    ports:
      - "8081:8081"
    volumes:
      - ../frontend/src:/app/src
      - ../frontend/index.html:/app/index.html
    stdin_open: true
    tty: true
    restart: always
    depends_on:
      - captcha_backend
    networks:
      - captcha

  mongodb:
    image: mongo
    container_name: 'mongodb'
    restart: always
    # ports:
    #  - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'admin'
      MONGO_INITDB_ROOT_PASSWORD: 'password'
    volumes:
      - mongodb_data:/var/lib/mongodb/data
    networks:
      - captcha

networks:
  captcha:
    driver: bridge

volumes:
  mongodb_data:
